# Generated by Django 5.0.dev20230611125713 on 2023-07-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0004_rename_customer_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(to='mini_social.customuser'),
        ),
    ]
