# Generated by Django 4.2.2 on 2023-08-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_social', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
